"""add_timestamps_and_cascade

Revision ID: 016accbe37d4
Revises: a1b2c3d4e5f6
Create Date: 2026-02-13 13:49:41.214906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "016accbe37d4"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventories",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "inventories",
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.drop_constraint(op.f("stocks_product_id_fkey"), "inventories", type_="foreignkey")
    op.drop_constraint(op.f("stocks_tenant_id_fkey"), "inventories", type_="foreignkey")
    op.create_foreign_key(None, "inventories", "products", ["product_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "inventories", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE")
    op.add_column(
        "products", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "products", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "tenants", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "tenants", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "users", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.drop_constraint(op.f("users_tenant_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "tenants", ["tenant_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(op.f("users_tenant_id_fkey"), "users", "tenants", ["tenant_id"], ["id"])
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("tenants", "updated_at")
    op.drop_column("tenants", "created_at")
    op.drop_column("products", "updated_at")
    op.drop_column("products", "created_at")
    op.drop_constraint(None, "inventories", type_="foreignkey")
    op.drop_constraint(None, "inventories", type_="foreignkey")
    op.create_foreign_key(op.f("stocks_tenant_id_fkey"), "inventories", "tenants", ["tenant_id"], ["id"])
    op.create_foreign_key(op.f("stocks_product_id_fkey"), "inventories", "products", ["product_id"], ["id"])
    op.drop_column("inventories", "updated_at")
    op.drop_column("inventories", "created_at")
    # ### end Alembic commands ###
