"""tenant name

Revision ID: 0e0ccc22938b
Revises: ae72ccbd7863
Create Date: 2026-02-13 10:04:16.689086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0e0ccc22938b"
down_revision: Union[str, Sequence[str], None] = "ae72ccbd7863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "name")
    # ### end Alembic commands ###
