"""user create

Revision ID: ae72ccbd7863
Revises: c8f145d18b8d
Create Date: 2026-02-12 20:14:45.328162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ae72ccbd7863"
down_revision: Union[str, Sequence[str], None] = "c8f145d18b8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_full_name"), "users", ["full_name"], unique=False)
    op.drop_index(op.f("ix_stocks_tenant_id"), table_name="inventories")
    op.drop_constraint(op.f("uq_tenant_product_inventory"), "inventories", type_="unique")
    op.create_index(op.f("ix_inventories_tenant_id"), "inventories", ["tenant_id"], unique=False)
    op.create_unique_constraint("uq_tenant_product_stock", "inventories", ["tenant_id", "product_id"])
    op.drop_constraint(op.f("tenants_email_key"), "tenants", type_="unique")
    op.drop_column("tenants", "email")
    op.drop_column("tenants", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("tenants", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(
        op.f("tenants_email_key"),
        "tenants",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("uq_tenant_product_stock", "inventories", type_="unique")
    op.drop_index(op.f("ix_inventories_tenant_id"), table_name="inventories")
    op.create_unique_constraint(
        op.f("uq_tenant_product_inventory"),
        "inventories",
        ["tenant_id", "product_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_stocks_tenant_id"), "inventories", ["tenant_id"], unique=False)
    op.drop_index(op.f("ix_users_full_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
